language: java

jdk:
- oraclejdk8

env:
  global:
    - ANDROID_SDK_VERSION="r22.6.2"
    - GRAILS_VERSION=2.4.3
    
android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-22.0.1
    - extra
  
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

before_install:
    #ANDROID
    - cd MeetingPlanner
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get update; fi
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - chmod +x gradlew
    #GRAILS
    - cd ../server/mplanner
    - rm -rf ~/.gvm
    - curl -s get.gvmtool.net > ~/install_gvm.sh
    - chmod 775 ~/install_gvm.sh
    - ~/install_gvm.sh
    - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
    - source ~/.gvm/bin/gvm-init.sh
    - gvm install grails $GRAILS_VERSION || true

branches:
  only:
    - master

notifications:
  email: true
 
script:
    - grails clean && grails test-app && grails prod war --stacktrace
    - cd ../../MeetingPlanner
    - ./gradlew tasks --all
    - ./gradlew init
    - ./gradlew androidDependencies
    - ./gradlew clean
    - ./gradlew build
    - ls
