language: java

jdk:
- oraclejdk8

env:
  - GRAILS_VERSION=2.4.3

before_install:
- cd server/mplanner
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true
- sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch

branches:
  only:
    - master

script: grails clean && grails test-app --non-interactive --stacktrace

after_script:
    - cd ../MeetingPlanner
    - ./gradlew clean build
    
