language: android

android:
  components:
    - platform-tools
    - tools
    - android-22
    - build-tools-21.1.1
    - extra
  
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

jdk:
    - oraclejdk8

os:
    - linux

env:
  global:
    - GRAILS_VERSION=2.4.3

notifications:
  email: true
 
 branches:
  only:
    - master

before_install:
    #ANDROID
    - cd MeetingPlanner
    - sudo apt-get update -qq
    - chmod +x gradlew
    #GRAILS
    - cd ../server/mplanner
    - rm -rf ~/.gvm
    - curl -s get.gvmtool.net > ~/install_gvm.sh
    - chmod 775 ~/install_gvm.sh
    - ~/install_gvm.sh
    - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
    - source ~/.gvm/bin/gvm-init.sh
    - gvm install grails $GRAILS_VERSION || true

script:
    - grails clean && grails test-app && grails prod war --stacktrace
    - cd ../../MeetingPlanner
    - ./gradlew tasks --all
    - ./gradlew init
    - ./gradlew androidDependencies
    - ./gradlew clean
    - ./gradlew build
    - ./gradlew assembleDebug
