language: groovy, android

jdk:
- oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - extra-android-support
    - extra-android-m2repository
    - android-22
  licenses:
    - '.+'

env:
  - GRAILS_VERSION=2.4.3

before_install:
- cd server/mplanner
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo "gvm_auto_answer=true" > ~/.gvm/etc/config
- source ~/.gvm/bin/gvm-init.sh
- gvm install grails $GRAILS_VERSION || true

branches:
  only:
    - master

script:
    - grails clean && grails test-app --non-interactive --stacktrace
    - ./gradlew clean assemble check
